# Generated by Django 5.1.3 on 2024-12-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id_refaccion', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_refaccion', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=100)),
                ('id_provedor', models.PositiveIntegerField()),
            ],
        ),
    ]
