# Generated by Django 5.1.3 on 2024-12-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('numero_de_cel', models.PositiveIntegerField()),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
    ]
