# Generated by Django 5.1.3 on 2024-12-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('num_cel', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
